# Generated by Django 5.2 on 2025-09-03 13:54

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armario', models.CharField(choices=[('Armário 1', 'Armário 1'), ('Armário 2 ', 'Armário 2 '), ('Armário 3', 'Armário 3'), ('Armário 4', 'Armário 4'), ('Armário 5', 'Armário 5'), ('Armário 7', 'Armário 7'), ('Armário 5 Chefia', 'Armário 5 Chefia'), ('Armário 17', 'Armário 17'), ('Armário 8', 'Armário 8'), ('Armário 20', 'Armário 20'), ('Armário 16', 'Armário 16'), ('Armário 19', 'Armário 19')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('matricula', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('avatar', models.ImageField(default='...', null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Samsung Galaxy A72', 'Samsung Galaxy A72'), ('Samsung Galaxy A23', 'Samsung Galaxy A23'), ('Outro', 'Outro')], max_length=100)),
                ('modelo', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Outros', 'Outros')], max_length=100)),
                ('patrimônio', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='/static/images/item.png', null=True, upload_to='items/')),
                ('IMEI', models.CharField(max_length=100, unique=True)),
                ('ICCID', models.CharField(max_length=100, unique=True)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('documento', models.CharField(max_length=200)),
                ('armario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armarios_celulares', to='base.armario')),
                ('cautela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_item_celulares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Algema plástica', 'Algema plástica'), ('Arame Lacre Laranja', 'Arame Lacre Laranja'), ('Barraca NTK Panda 3', 'Barraca NTK Panda 3'), ('Bermuda Masc.', 'Bermuda Masc.'), ('Boné com Capa', 'Boné com Capa'), ('Boné Ibama', 'Boné Ibama'), ('Boné Legionário', 'Boné Legionário'), ('Bota Galocha', 'Bota Galocha'), ('Bota SL Branca', 'Bota SL Branca'), ('Bota SL Pró Preta', 'Bota SL Pró Preta'), ('Bota Térmica', 'Bota Térmica'), ('Botas Seasub', 'Botas Seasub'), ('Calça', 'Calça'), ('Calça Fem.', 'Calça Fem.'), ('Calça Masc.', 'Calça Masc.'), ('Calça/Bermuda Masc.', 'Calça/Bermuda Masc.'), ('Camisa  Fisc. Manga Curta ', 'Camisa  Fisc. Manga Curta '), ('Camisa  Fisc. Manga Longa ', 'Camisa  Fisc. Manga Longa '), ('camisa polo', 'camisa polo'), ('Camiseta Branca manga curta', 'Camiseta Branca manga curta'), ('Camiseta Branca manga longa', 'Camiseta Branca manga longa'), ('Camiseta Verde manga longa', 'Camiseta Verde manga longa'), ('Cantil', 'Cantil'), ('Capa de Chuva Comum', 'Capa de Chuva Comum'), ('Capa de Chuva Morcego Reflexiva ', 'Capa de Chuva Morcego Reflexiva '), ('Capa de Chuva Morcego S/Refletores ', 'Capa de Chuva Morcego S/Refletores '), ('Capa de chuva Neon', 'Capa de chuva Neon'), ('Capa Externa de Colete Balístico  PROTECTA - VERDE', 'Capa Externa de Colete Balístico  PROTECTA - VERDE'), ('Capa Externa de Colete Balístico  TAURUS - PRETA', 'Capa Externa de Colete Balístico  TAURUS - PRETA'), ('capa impermeável p/mochila rusher', 'capa impermeável p/mochila rusher'), ('Capa para Cantil', 'Capa para Cantil'), ('Capacete 3M Branco', 'Capacete 3M Branco'), ('Capacete de segurança UMP Amarelo ', 'Capacete de segurança UMP Amarelo '), ('Chapéu com Proteção ', 'Chapéu com Proteção '), ('Cinto Tático  ', 'Cinto Tático  '), ('Cinto Tático Underbelt', 'Cinto Tático Underbelt'), ('Cintos Verde', 'Cintos Verde'), ('Colete de Segurança', 'Colete de Segurança'), ('Colete em X Verde e Branco ', 'Colete em X Verde e Branco '), ('Colete Fisc.', 'Colete Fisc.'), ('Colete Flotek', 'Colete Flotek'), ('Colete Laranja e Branco', 'Colete Laranja e Branco'), ('Colete Reflexivo', 'Colete Reflexivo'), ('Coturno', 'Coturno'), ('Coturno Prevfogo', 'Coturno Prevfogo'), ('Encaixe Toyota p/ Calota', 'Encaixe Toyota p/ Calota'), ('Facão', 'Facão'), ('Fita adesiva larga - IBAMA/MMA', 'Fita adesiva larga - IBAMA/MMA'), ('Gandola ', 'Gandola '), ('Japona Térmica', 'Japona Térmica'), ('Jaqueta com forro', 'Jaqueta com forro'), ('Laminado Respirável', 'Laminado Respirável'), ('Lanterna de Cabeça ALFACELL', 'Lanterna de Cabeça ALFACELL'), ('Luva Latéx Descartável Volk', 'Luva Latéx Descartável Volk'), ('Luva Nitrilica-Tam-Único', 'Luva Nitrilica-Tam-Único'), ('Luvas de vaqueta Alseg – CA 25368', 'Luvas de vaqueta Alseg – CA 25368'), ('Macacão Flytec', 'Macacão Flytec'), ('Macacão Impermeável Laminado', 'Macacão Impermeável Laminado'), ('Manta Alcochoada', 'Manta Alcochoada'), ('Máscara PFF1', 'Máscara PFF1'), ('Mochila', 'Mochila'), ('Mochila de Salvamento', 'Mochila de Salvamento'), ('Mochila IBAMA', 'Mochila IBAMA'), ('Mochila Rusher 40L Verde', 'Mochila Rusher 40L Verde'), ('Mochilas de Hidratação KALAHARI', 'Mochilas de Hidratação KALAHARI'), ('Mucambo Pro AF 15', 'Mucambo Pro AF 15'), ('Óculos de proteção Kalipso', 'Óculos de proteção Kalipso'), ('Perneira  ', 'Perneira  '), ('Perneira Sayro - CA 14750', 'Perneira Sayro - CA 14750'), ('Porta Rádio', 'Porta Rádio'), ('Porta utilidades P/ Cinto', 'Porta utilidades P/ Cinto'), ('Protetor auricular silicone – CA 18189', 'Protetor auricular silicone – CA 18189'), ('Regulador de capacete', 'Regulador de capacete'), ('Sapato Couro', 'Sapato Couro'), ('Sobretudo Impemeável ', 'Sobretudo Impemeável '), ('Touca TNT Descartável', 'Touca TNT Descartável'), ('Trena de Fibra', 'Trena de Fibra'), ('Headset Logitech', 'Headset Logitech'), ('Camera WEBCAM Gotech', 'Camera WEBCAM Gotech'), ('Kit Identificador de Gás Refrigerante', 'Kit Identificador de Gás Refrigerante')], max_length=200)),
                ('quantidade', models.IntegerField()),
                ('patrimônio', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='/static/images/item.png', null=True, upload_to='items/')),
                ('tamanho', models.CharField(choices=[('XG', 'XG'), ('Único', 'Único'), ('PP', 'PP'), ('P', 'P'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('EG', 'EG'), ('52', '52'), ('50', '50'), ('48', '48'), ('46', '46'), ('44', '44'), ('43', '43'), ('42', '42'), ('41', '41'), ('39', '39'), ('38', '38'), ('37', '37'), ('36', '36'), ('13', '13')], max_length=100)),
                ('armario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armarios', to='base.armario')),
                ('cautela_inicial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cautela_inicial', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Algema plástica', 'Algema plástica'), ('Arame Lacre Laranja', 'Arame Lacre Laranja'), ('Barraca NTK Panda 3', 'Barraca NTK Panda 3'), ('Bermuda Masc.', 'Bermuda Masc.'), ('Boné com Capa', 'Boné com Capa'), ('Boné Ibama', 'Boné Ibama'), ('Boné Legionário', 'Boné Legionário'), ('Bota Galocha', 'Bota Galocha'), ('Bota SL Branca', 'Bota SL Branca'), ('Bota SL Pró Preta', 'Bota SL Pró Preta'), ('Bota Térmica', 'Bota Térmica'), ('Botas Seasub', 'Botas Seasub'), ('Calça', 'Calça'), ('Calça Fem.', 'Calça Fem.'), ('Calça Masc.', 'Calça Masc.'), ('Calça/Bermuda Masc.', 'Calça/Bermuda Masc.'), ('Camisa  Fisc. Manga Curta ', 'Camisa  Fisc. Manga Curta '), ('Camisa  Fisc. Manga Longa ', 'Camisa  Fisc. Manga Longa '), ('camisa polo', 'camisa polo'), ('Camiseta Branca manga curta', 'Camiseta Branca manga curta'), ('Camiseta Branca manga longa', 'Camiseta Branca manga longa'), ('Camiseta Verde manga longa', 'Camiseta Verde manga longa'), ('Cantil', 'Cantil'), ('Capa de Chuva Comum', 'Capa de Chuva Comum'), ('Capa de Chuva Morcego Reflexiva ', 'Capa de Chuva Morcego Reflexiva '), ('Capa de Chuva Morcego S/Refletores ', 'Capa de Chuva Morcego S/Refletores '), ('Capa de chuva Neon', 'Capa de chuva Neon'), ('Capa Externa de Colete Balístico  PROTECTA - VERDE', 'Capa Externa de Colete Balístico  PROTECTA - VERDE'), ('Capa Externa de Colete Balístico  TAURUS - PRETA', 'Capa Externa de Colete Balístico  TAURUS - PRETA'), ('capa impermeável p/mochila rusher', 'capa impermeável p/mochila rusher'), ('Capa para Cantil', 'Capa para Cantil'), ('Capacete 3M Branco', 'Capacete 3M Branco'), ('Capacete de segurança UMP Amarelo ', 'Capacete de segurança UMP Amarelo '), ('Chapéu com Proteção ', 'Chapéu com Proteção '), ('Cinto Tático  ', 'Cinto Tático  '), ('Cinto Tático Underbelt', 'Cinto Tático Underbelt'), ('Cintos Verde', 'Cintos Verde'), ('Colete de Segurança', 'Colete de Segurança'), ('Colete em X Verde e Branco ', 'Colete em X Verde e Branco '), ('Colete Fisc.', 'Colete Fisc.'), ('Colete Flotek', 'Colete Flotek'), ('Colete Laranja e Branco', 'Colete Laranja e Branco'), ('Colete Reflexivo', 'Colete Reflexivo'), ('Coturno', 'Coturno'), ('Coturno Prevfogo', 'Coturno Prevfogo'), ('Encaixe Toyota p/ Calota', 'Encaixe Toyota p/ Calota'), ('Facão', 'Facão'), ('Fita adesiva larga - IBAMA/MMA', 'Fita adesiva larga - IBAMA/MMA'), ('Gandola ', 'Gandola '), ('Japona Térmica', 'Japona Térmica'), ('Jaqueta com forro', 'Jaqueta com forro'), ('Laminado Respirável', 'Laminado Respirável'), ('Lanterna de Cabeça ALFACELL', 'Lanterna de Cabeça ALFACELL'), ('Luva Latéx Descartável Volk', 'Luva Latéx Descartável Volk'), ('Luva Nitrilica-Tam-Único', 'Luva Nitrilica-Tam-Único'), ('Luvas de vaqueta Alseg – CA 25368', 'Luvas de vaqueta Alseg – CA 25368'), ('Macacão Flytec', 'Macacão Flytec'), ('Macacão Impermeável Laminado', 'Macacão Impermeável Laminado'), ('Manta Alcochoada', 'Manta Alcochoada'), ('Máscara PFF1', 'Máscara PFF1'), ('Mochila', 'Mochila'), ('Mochila de Salvamento', 'Mochila de Salvamento'), ('Mochila IBAMA', 'Mochila IBAMA'), ('Mochila Rusher 40L Verde', 'Mochila Rusher 40L Verde'), ('Mochilas de Hidratação KALAHARI', 'Mochilas de Hidratação KALAHARI'), ('Mucambo Pro AF 15', 'Mucambo Pro AF 15'), ('Óculos de proteção Kalipso', 'Óculos de proteção Kalipso'), ('Perneira  ', 'Perneira  '), ('Perneira Sayro - CA 14750', 'Perneira Sayro - CA 14750'), ('Porta Rádio', 'Porta Rádio'), ('Porta utilidades P/ Cinto', 'Porta utilidades P/ Cinto'), ('Protetor auricular silicone – CA 18189', 'Protetor auricular silicone – CA 18189'), ('Regulador de capacete', 'Regulador de capacete'), ('Sapato Couro', 'Sapato Couro'), ('Sobretudo Impemeável ', 'Sobretudo Impemeável '), ('Touca TNT Descartável', 'Touca TNT Descartável'), ('Trena de Fibra', 'Trena de Fibra'), ('Headset Logitech', 'Headset Logitech'), ('Camera WEBCAM Gotech', 'Camera WEBCAM Gotech'), ('Kit Identificador de Gás Refrigerante', 'Kit Identificador de Gás Refrigerante')], max_length=200)),
                ('quantidade', models.IntegerField()),
                ('patrimônio', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='./static/images/item.png', null=True, upload_to='')),
                ('tamanho', models.CharField(choices=[('XG', 'XG'), ('Único', 'Único'), ('PP', 'PP'), ('P', 'P'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('EG', 'EG'), ('52', '52'), ('50', '50'), ('48', '48'), ('46', '46'), ('44', '44'), ('43', '43'), ('42', '42'), ('41', '41'), ('39', '39'), ('38', '38'), ('37', '37'), ('36', '36'), ('13', '13')], max_length=100)),
                ('armario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.armario')),
                ('cautela', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='servidor', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patrimônio', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='/static/images/item.png', null=True, upload_to='items/')),
                ('acessório_1', models.CharField(blank=True, max_length=100, null=True)),
                ('acessório_2', models.CharField(blank=True, max_length=100, null=True)),
                ('acessório_3', models.CharField(blank=True, max_length=100, null=True)),
                ('acessório_4', models.CharField(blank=True, max_length=100, null=True)),
                ('acessório_5', models.CharField(blank=True, max_length=100, null=True)),
                ('acessório_6', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(max_length=200)),
                ('armario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armarios_notebooks', to='base.armario')),
                ('cautela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cautela_notebooks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_item_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
