# Generated by Django 5.2 on 2025-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armario',
            name='armario',
            field=models.CharField(choices=[('Armário 1', 'Armário 1'), ('Armário 2 ', 'Armário 2 '), ('Armário 3', 'Armário 3'), ('Armário 4', 'Armário 4'), ('Armário 5', 'Armário 5'), ('Armário 7', 'Armário 7'), ('Armário 5 Chefia', 'Armário 5 Chefia'), ('Armário 17', 'Armário 17'), ('Armário 8', 'Armário 8'), ('Armário 20', 'Armário 20'), ('Armário 16', 'Armário 16'), ('Armário 19', 'Armário 19'), ('Externo', 'Externo')], max_length=30),
        ),
    ]
