# Generated by Django 5.2 on 2025-06-26 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='cautela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='...', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='patrimônio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
