# mysite_nginx.conf

# configuration of the server
server {
    # the port your site will be served on
    listen      80;
    # the domain name it will serve for
    server_name <10.11.1.128>; # substitute your machine's IP address or FQDN
    charset     utf-8;

    # max upload size
    client_max_body_size 75M;   # adjust to taste

    # Django media
    location /media  {
        alias /media; # your Django project's media files - amend as required
    }

    location static/ {
        alias C:/Users/33518197819.IBAMA/Desktop/Git/cmd/meuprojeto_base/staticfiles/; # your Django project's static files - amend as required
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        proxy_pass http://10.11.1.128:80; # See output from runserver.py
    }
}